version: "3.9"

services:
  
  api:
    build:
      context: .
      dockerfile: problems/problem-1/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=interview_user
      - POSTGRES_PASSWORD=interview_password
      - POSTGRES_DB=interview_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432


  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db_data:



