version: "3.9"

services:
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8000:8000"
    volumes:
      - ./order-service/app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
